### PR TITLE
fix(api): fixed the the app.e2e-spec.ts by mocking the PrismaService

### LINKED ISSUE #64: Roadmap 2023
- [ ] 1. #65
- [ ] 2. #66
	- [ ] #144
- [ ] 3. #67
- [ ] 4. API Specification
	- [ ] #69
	- [ ] #70
	- [ ] #71
	- [ ] #72
	- [ ] #73
- [ ] 5. UI
	- [ ] #74
	- [ ] #75
	- [ ] #76
- [ ] 6. Deployment Setup
	- [ ] #77
	- [ ] #78
- [ ] 7. Plugins
	- [ ] 7.1 Templates Supported
	    - [ ] #79
	    - [ ] #80
	    - [ ] #81
	    - [ ] #82 
	    - [ ] #84 
	    - [ ] #86 
	    - [ ] #87 
    - [ ] 7.2 Input plugins
		- [ ] #83
		- [ ] #85
	- [ ] 7.3 Output plugins
		- [ ] #88
		- [ ] #89
		- [ ] #90
		- [ ] #91
		- [ ] #92
		- [ ] #93
    - [ ] 7.4 Delivery plugins
		- [ ] #94
		- [ ] #95
    - [ ] 7.5 Storage plugins
		- [ ] #96
		- [ ] #97
		- [ ] #98
		- [ ] #99
- [ ] 8. #100
- [ ] 9. #101

### LINKED ISSUE #132: Fix AppController end-to-end testcase
There is an e2e test case in this file `test/app.e2e-spec.ts` that simply hit the`/api` endpoint and tests if it prints `Doc Generator` or not. 
So currently this test case is failing because the required dependencies are not available to it for example Prisma service is not available to it, we can pass the instance but in this case, we don't want to pass the actual Prisma service instance rather we want to **mock** it because we don't want this test to be dependent on the database. 

See https://github.com/Samagra-Development/Doc-Generator/blob/Roadmap-2023/test/app.e2e-spec.ts#L10-L13 for reference.

### PR DESCRIPTION
**Pull request by VarunGitGood**
changed the file layout a bit there was no PrimsaModule so used nest CLI to generate it made sure everythingworks

closes #132

### CODE REVIEW

**Comment by VarunGitGood** [comment]
@AnshulMalik @yuvrajsab can you please review this 

Thanks!!

**Comment by AnshulMalik** [comment]
Hey @varun7singh, Thanks for the PR.

The current mock approach, we won't be able to test the actual functionality in future, we need to mock the client, but should behave like prisma client and not connect to actual database at the same time.

Here is how the official documentation suggests:
https://www.prisma.io/docs/guides/testing/unit-testing

**Comment by VarunGitGood** [comment]
Oh okay sure 
Thanks !! will look into it and commit again

**Comment by VarunGitGood** [comment]
@AnshulMalik do look into this PR i referred to the docs and use mockDeep to create a mock instance of PrismaService 

do let me know for any more changes 

Thanks !!

**Review by AnshulMalik — APPROVED** [review]

**Pull request merged**
